// Generated by LiveScript 1.2.0
(function(){
  var fontPath, eudc, text, res$, i$, i;
  console.log(opentype);
  fontPath = '../font/';
  eudc = 'cdpeudc.tte';
  res$ = [];
  for (i$ = 5797; i$ <= 5813; ++i$) {
    i = i$;
    res$.push(String.fromCharCode(57344 + i));
  }
  text = res$;
  opentype.load(fontPath + "" + eudc, function(err, font){
    var ctx, path;
    if (err) {
      console.log("Fail to load " + eudc + ": " + err);
    } else {
      ctx = document.getElementById('canvas').getContext('2d');
      path = font.getPath(text.join(''), 0, 50, 32);
      path.draw(ctx);
    }
  });
}).call(this);
